### PR TITLE
initialized the front end with connect wallet

### PR DESCRIPTION
**Pull request by YohanTz**
Initialized the game front end with Typescript, Next.js, and Tailwind with a simple connect wallet button

### CODE REVIEW

**Review by hypekn1ght — COMMENTED** [review]
Apart from the deleted midjourney assets, all looks good !

**Review by hypekn1ght — APPROVED** [review]

**Comment by YohanTz** [comment]
> Apart from the deleted midjourney assets, all looks good !

Yes ! They changed a lot in the designs so I removed them

**Comment by LucasLvy** [comment]
trigger vercel

**Review by LucasLvy — APPROVED** [review]
lgtm

**Pull request merged**
