### PR TITLE
feat(frontend): add card component

### LINKED ISSUE #5: Card design
# Description

According to the [game rules](https://github.com/keep-starknet-strange/tsubasa/discussions/2#discussioncomment-6567694) we need to design multiple cards (depending on the rarity).
Each card will have at least:
* Player name
* Attack
* Defense
* Image of the player

# Acceptance criteria

* We'll schedule a meeting with Starkware/Dojo/Designer to validate the design

### PR DESCRIPTION
**Pull request by remiroyc**
Fix #5

### CODE REVIEW

**Comment by remiroyc** [comment]
cc @clicksave @LucasLvy

1 -  Related to this question https://t.me/TsubasaStarknet/489
This is the current integration:  https://tsubasa-git-fork-remiroyc-feat-card-keep-starknet-strange.vercel.app/cards what do you think?

2 - Where do you plan to save player images? I don't believe you've generated the complete collection yet. In my view, this should be addressed in a separate issue. For the time being, I recommend creating cards without player images, similar to some of the cards in my link.

**Comment by LucasLvy** [comment]
Screenshot 2023-08-16 at 17 11 13
There is a problem in the star placement i think

**Comment by clicksave** [comment]
> cc @clicksave @LucasLvy
> 
> 1 - Related to this question https://t.me/TsubasaStarknet/489 The card has a set size determined by the developer based on context (size param "xl", "lg", "md", "sm", "xs"), rather than being tied to the screen resolution. Sample: https://tsubasa-git-fork-remiroyc-feat-card-keep-starknet-strange.vercel.app/cards what do you think?
> 
> 2 - Where do you plan to save player images? I don't know if you've generated the complete collection yet. In my view, this should be addressed in a separate issue. For the time being, I recommend creating cards without player images, similar to some of the cards in my link.

Nice! these are looking great. particularly on the larger versions of the cards. Awesome to see them in the different sizes. Feels good. Am noticing a few things that could be improved

image

- [ ]  Border feels heavier than it is in the mockups. Currently 4px -> ideally: 2px
- [ ]  Captain star should be center aligned in the container and the container should be vertically center aligned to the top of the card. 

image

- [ ]  Background shape of the energy cost component could scale better. There should be more padding on smaller sizes 

image

- [ ] Seeing some weird clipping on the drop shadow for the attribute components 

image

- [ ] Border radius on the attribute components is too aggressive at smaller size. it should be less intense as the cards get smaller

image

- [ ] The attribute component has some padding issues at smaller sizes too. Icon is too close to the bottom edge

image

- [ ] the position of the attribute component on the card is a bit different than the mockups at smaller sizes. It should be closer to the edge. this property is variable depending on the card size

image

- [ ] The image border radius and the card border radius should be the same, atm theres a discrepancy between them and you can see the background 

image

- [ ] Would prefer to use a vector for this tsubasa holographic thing than a png, I think we can also just remove it if that feels like too much 

image


---

Here's a link the the finalized illustrations

https://github.com/keep-starknet-strange/tsubasa/discussions/11#discussioncomment-6742425

**Comment by LucasLvy** [comment]
Screenshot 2023-08-18 at 16 05 32
There is a `g` at the top of the frame, seems like it's not present on the main branch, can you remove that plz ?

**Comment by remiroyc** [comment]
cc @clicksave

**Review by LucasLvy — APPROVED** [review]
lgtm

**Pull request merged**
